version: '3.1'

services:
  jekyll:
    image: jekyll/minimal
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle

volumes:
  bundle_cache:
